name: dev

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name:ml-horizon
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requeriments.txt
    - name: Run Project
      run: |
        cd src && python3 run.py        
.